schema_version = "1.0.0"

id = "sculptools_palette"
version = "1.0.0"
name = "Sculptools: Palette"
tagline = "Radial palette for sculpt brushes and tools"
maintainer = "Argo"
type = "add-on"
website = "https://github.com/ProjectArgo-dev/Sculptools_Palette"

tags = ["Sculpt", "User Interface"]

blender_version_min = "4.5.0"

license = ["SPDX:GPL-3.0-or-later"]

copyright = [
  "2026 Argo",
  "2002-2024 Blender Authors (bundled Sculpt tool icons)",
]
